version: '2'

services:
  bind:
    restart: always
    image: sameersbn/bind:9.9.5-20161106
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "67:67/udp"
    - "68:68/udp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data:rw
    - ./sample/DHCP/dhcpd.conf:/etc/dhcp/dhcpd.conf:rw
